### ISSUE TITLE
Swup gets stuck when replacing head

### ISSUE THREAD

**Issue by nncrns** [swup/head-plugin#13]
I want to replace canonical and hreflang links on each page, so I installed this plugin normally: 

```javascript
import SwupHeadPlugin from '@swup/head-plugin';
const swup = Swup(plugins: [new SwupHeadPlugin()]);
```

However, once it is installed and I navigate from the starting page to a new page, swup gets stuck on `swup-enabled is-changing to-my-new-page is-rendering`, and the page layout "breaks" (no css applied, scripts seem to work). No console errors.

The head is correctly replaced at first, however once it is stuck and layout "broken", neither content nor head are replaced anymore.

What could be the issue here? It can't have to do with another "transition" class (as was the case in another issue.) Thanks a lot for any help!

**Comment by gmrchk** [comment]
Hi, sorry for the delay!
I think the problem is that the head plugin also replaces some of your linked styles, that are not present on the next page. During that, the styles for transition are probably removed as well, which makes swup wait for a transition that will never happen/finish. In case the same style with transitions is present on the next page, the plugin shouldn't remove it, so placing it on every page should fix the issue. 

Head plugin is now also enhanced with some new functionality for ignoring specific tags and not removing them, so you can also give that a try.

I will close this as part of the clean-up of old issues but feel free to reopen if you still need help.
