### ISSUE TITLE
Safe to use this plugin?

### ISSUE THREAD

**Issue by aerni** [swup/head-plugin#2]
I've been running into the common issue with `<link rel="canonical" href="..." />` in the head. In the docs you mention that this plugin is "rather experimental". What exactly do you mean by this? Is it safe to use in production? 

Also, does this plugin exchange the whole `<head>`? Can't we just change the canonical meta tags? Would that make this plugin "safer"?

**Comment by aerni** [comment]
I noticed that important scripts in the head get removed like Google Tag Manager or Font Awesome. Is it possible to have this plugin solely take care of the meta tags?

**Comment by aerni** [comment]
@gmrchk What's the state of this?

**Comment by AugustMiller** [comment]
@aerni Thanks for your patience! Georgy's efforts are focused on the main Swup plugin, and I've only just seen your question.

I think "safe" to use is a fair assessment, although we'd recommend that you understand the ramifications of adding + removing `head` content between pages.

The plugin is actually _super_ crude... it just iterates over the incoming children of the `head` element and compares them with existing ones:

1) If the tag is new, it's inserted.
2) If it matches an existing one, nothing is done with the existing tag (to prevent, say, flashes of un-styled content).
3) If a tag is not present in the new page, it's removed.

The comparisons are all done at the markup level: if the `outerHTML` of the two DOM nodes match, they're considered to be the same.

Overall, I suspect Georgy's inclusion of the warning was due to the simplicity of the implementation, not because it's dangerous.

One important usage note: _if you need a tag in the `head` of every page, it should be on every page that the server returns_, and leave nothing to configure or filter out in the client (In reply to [this comment](#issuecomment-547885669)). The plugin tries to emulate as close to a complete page replacement as possible, while still keeping things seamless.

Could you provide some more information about the `canonical` issue you're experiencing? I don't see any other open issues about this.

**Comment by aerni** [comment]
@AugustMiller There's a whole bunch of `meta` and `link` tags that are not being replaced by this plugin. See the three screenshots of my website below. The first two screenshots show the `head` when directly opening the URL in the browser. The third screenshot shows the `head` when navigating from `/en/` to `/en/work/`. The website is [michaelaerni.ch](https://www.michaelaerni.ch/en)

**Page: `/en/`**
<img width="2032" alt="Home" src="https://user-images.githubusercontent.com/23167701/71622943-763f9f00-2bd9-11ea-8c56-857d2a90cb4c.png">

**Page: `/en/work`**
<img width="2032" alt="Work" src="https://user-images.githubusercontent.com/23167701/71622947-7c358000-2bd9-11ea-9678-3a83f0e7ce3a.png">

**Page `/en/` to `/en/work`**
<img width="2032" alt="Home- Work" src="https://user-images.githubusercontent.com/23167701/71622954-86577e80-2bd9-11ea-9c11-c830712b7cc6.png">

**Comment by aerni** [comment]
Nevermind. I actually disabled the head plugin due to some other issues I've encountered with it. When starting to investigate the issues again, I didn't remember that I previously had disabled the plugin on production. My bad.

I'm going to open another issue with the issues I've encountered.
